global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ivan_kuchin'
