version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    #build: ../src/ui/
    image: mersey/ui:${VERSIONUI}
    ports:
      - ${PORTUI}:9292/tcp
    networks:
      - reddit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    #build: ../src/post-py/
    image: mersey/post:${VERIOSNPOST}
    networks:
      - reddit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    #build: ../src/comment/
    image: mersey/comment:${VERSIONCOMMENT}
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      
volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
