kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: gq6NP+nLhjfgMSKNWnTx7GldxL/nRQ8CriPdDMQbg1E=
      - identity: {}
