version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSIONUI}
    ports:
      - ${PORTUI}:9292/tcp
    networks:
      - reddit

  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERIOSNPOST}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSIONCOMMENT}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
